#!/bin/sh

syscond_dir=$HOME/devel/shell/syscond
check_dir=$syscond_dir/check

Main() {
	if [ "$#" -lt 1 ]; then
	    echo "Usage: syscond command" >&2
	    exit 1
	fi

	arg=$1

	case $arg in
	    check)
		shift
		CommandCheck $*
		;;

	    *)
		echo "Unknown command $*" >&2
		exit 2
		;;
	esac
}

CommandCheck() {
    if [ "$#" -ne 1 ]; then
	echo "Usage: syscond check day | hour | minute" >&2
	exit 3
    fi

    dir=$1

    case $dir in
	day)
	    ;;
	hour)
	    ;;
        minute)
	    ;;

	*)
	    echo "Usage: syscond check day | hour | minute" >&2
	    exit 4
	    ;;
    esac

    RunScriptsInDir $dir

}

RunScriptsInDir() {
    dir=$1

    for file in $check_dir/$dir/*; do
	RunScript $file
    done
}

RunScript() {
    script=$1

    if [ ! -x $script ]; then
	echo "Ignoring non-executable file $script."
	return 1
    fi

    $script
}

Main $*
