#!/bin/sh

log_file=$HOME/log/upd.log

yellow_threshold=28800 # 20 days
red_threshold=72000    # 50 days

cond=0

if [ ! -e "$log_file" ]; then
    echo "2\tupd as never been run."
    exit 0
fi

if test "`find $log_file -mmin +${red_threshold}`"; then
    echo "1\tIt has been more than 50 days since the last upd."
    exit 0
fi

if test "`find $log_file -mmin +${yellow_threshold}`"; then
    echo "1\tIt has been more than 20 days since the last upd."
    exit 0
fi

echo "0\tupd has been run within the last 20 days."
