#!/usr/bin/env python3

yellow_threshold = 4.0
red_threshold    = 6.0

with open("/proc/loadavg") as f:
    line = f.readline()

words = line.strip().split(" ")

load_avg = float(words[1])

if load_avg > red_threshold:
    cond = 2
elif load_avg > yellow_threshold:
    cond = 1
else:
    cond = 0

print("%d\tThe load average over the past five minutes is %.2f." \
          % (cond, load_avg))
