#!/bin/sh

num_err_files=0

err_files=$(find $HOME/log -name "*.err")

for file in $err_files; do
    if test -s $file; then	# If file exists and has non-zero size
	num_err_files=$(( $num_err_files + 1 ))
    fi
done

case $num_err_files in
    0)
	echo "0\tThere are no error files in \$HOME/log."
	exit 0
	;;

    1)
	echo "1\tThere is an error file in \$HOME/log."
	exit 0
	;;
    
    *)
	echo "2\tThere are several error files in \$HOME/log."
	;;
esac
