#!/bin/sh

yellow_threshold=85
red_threshold=95

cond=0

percent=$(df -m | grep " /$" | awk '{print $5}' | sed -e 's/%//')

if [ $? -ne 0 ]; then
    echo "2\tFailed to check rootfs."
    exit 1
fi
    
if [ $percent -gt $yellow_threshold ]; then
    cond=1
fi

if [ $percent -gt $red_threshold ]; then
    cond=2
fi

echo "$cond\tThe rootfs filesystem is $percent% full."
